### ISSUE TITLE
save network device config without overwriting previous file

### ISSUE THREAD

**Issue by mkazam** [ansible/network#3]
Hi,
I'm using Ansible 2.7 & the task below works fine but I'd like to change the save option so that the previously saved files are not overwritten.
Can someone please advise on how to make the required change.

tasks:
    - name: Backup sh run to files in output dir
      ios_command:
        provider:
          timeout: 30
        commands:
          - show run
      register: print_output

    - name: save output to a file
      copy: content="{{ print_output.stdout[0] }}" dest="./output/{{ inventory_hostname }}.txt"

Regards, mk

**Comment by cidrblock** [comment]
Ansible issues should be opened in ansible/ansible in the future, this repo isn't watched for issues currently.  

Try adding an timestamp to your output filename `{{ansible_date_time.date}}` this will allow previous files to be in place.
